version: "3.9"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: quote-dev
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - public_assets:/app/public

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: quote-editor
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  nginx-proxy:
    image: nginx
    container_name: quote-nginx
    ports:
      - "3001:80"
    restart: always
    depends_on:
      - webapp
    volumes:
      - public_assets:/var/www/quote-site/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pgdata:
  public_assets: