version: 0.0
os: linux

files:
  - source: docker-compose.yml
    destination: /home/ec2-user/app
  - source: nginx.conf
    destination: /home/ec2-user/app
  - source: .env
    destination: /home/ec2-user/app
  - source: scripts/deploy.sh
    destination: /home/ec2-user/app

permissions:
  - object: /home/ec2-user/app/scripts/deploy.sh
    pattern: +x

hooks:
  BeforeInstall:
    - location: scripts/dummy.sh
      timeout: 300
      runas: root

phases:
  ApplicationStart:
    commands:
      - /home/ec2-user/app/scripts/deploy.sh