version: '3.3'
services:
  webapp:
    image: phatnguyen1812/rails-app:latest
    container_name: quote-editor
    env_file:
      - .env
    command: ["bundle", "exec", "puma"]
    ports:
      - "3003:3000"
    restart: always
    volumes:
      - public_assets:/app/public

  sidekiq:
    image: phatnguyen1812/rails-app:latest
    container_name: quote-sidekiq
    env_file:
      - .env
    command: ["bundle","exec", "sidekiq"]
    restart: always

  nginx-proxy:
    image: nginx
    container_name: quote-nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - webapp
    volumes:
      - public_assets:/var/www/quote-site/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  public_assets: