version: '3.9'
services:
  webapp:
    image: 932782693588.dkr.ecr.ap-southeast-1.amazonaws.com/quote-app-default:${IMAGE_VERSION}
    container_name: quote-editor
    logging:
      driver: awslogs
      options:
        awslogs-group: ${log_group_name}
        awslogs-region: ap-southeast-1
        awslogs-stream-prefix: docker
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - public_assets:/app/public

  nginx-proxy:
    image: nginx
    container_name: quote-nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - webapp
    volumes:
      - public_assets:/var/www/quote-site/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: awslogs
      options:
        awslogs-group: ${log_group_name}
        awslogs-region: ap-southeast-1
        awslogs-stream-prefix: docker

volumes:
  public_assets: